import javax.swing.JOptionPane;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame17.java
 *
 * Created on 2 Feb, 2017, 11:33:50 AM
 */

/**
 *
 * @author shivam
 */
public class NewJFrame17 extends javax.swing.JFrame {

    /** Creates new form NewJFrame17 */
    public NewJFrame17() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList7 = new javax.swing.JList();
        jTextField8 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList8 = new javax.swing.JList();
        jTextField9 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("Drinks");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jList7.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jList7.setForeground(new java.awt.Color(102, 51, 0));
        jList7.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "None", "Tea", "Coffee", "Soft Drinks", "Cold Coffee", "Cold Coffee with Ice-Cream" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList7MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jList7);

        jPanel3.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 116, 130));

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField8.setText("0");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 121, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 380, 160, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 0));
        jLabel1.setText("Salad");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jList8.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jList8.setForeground(new java.awt.Color(51, 102, 0));
        jList8.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "None", "Green Salad", "Cucumber Salad", "Fruit Salad", "Dry Papad", "Fry Papad" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList8MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jList8);

        jPanel2.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 107, 127));

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField9.setText("0");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 107, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1125, 380, 130, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 245, 116, -1));

        jList1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jList1.setForeground(new java.awt.Color(102, 0, 0));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "None", "Paneer masala dosa", "Onion sada dosa", "Masala dosa", "Paper roast dosa", "Butter sada dosa", "Onion vada", "Sada vada", "Veg upma", "Sada upma", "Halwa(Sweet)", "Alu chop", "Idli", "Sambhar idli" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 59, 116, -1));

        jList2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jList2.setForeground(new java.awt.Color(102, 0, 0));
        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "None", "Dal fry", "Dal tadka", "Dal makini", "Mix vegetable curry", "Vegetable kurma", "Aloo dum", "Malai kofta", "Paneer tikka masala", "Kadai paneer", "Paneer butter masala", "Paneer bharta", "Aloo kobi", "Kobi masala" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 59, 120, -1));

        jList3.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jList3.setForeground(new java.awt.Color(102, 0, 0));
        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "None", "Veg sweet corn soup", "Hot/soup", "Lemon noodles soup", "Manchurian soup", "Tomato soup", "Mushroom soup", "Manchurian", "Noodles", "Veg haka noodles" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 59, 113, -1));

        jList4.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jList4.setForeground(new java.awt.Color(102, 0, 0));
        jList4.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "None", "Veg-American chopsuey", "Mushroom chilly", "Baby corn chilly", "Potato chilly", "Gobi chilly", "Chana masala", "Mattar paneer", "Mushroom curry", "Palak cream" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jList4);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 59, 116, -1));

        jList5.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jList5.setForeground(new java.awt.Color(102, 0, 0));
        jList5.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "None", "Plain rice", "Veg pulao", "Green peas pulao", "Sajan pulao", "Kashmiri pulao", "Veg fried rice", "Veg-biryani", "Jira-rice", "Lemon rice" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList5MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jList5);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 59, 111, -1));

        jList6.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jList6.setForeground(new java.awt.Color(102, 0, 0));
        jList6.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "None", "Tawa roti", "Tandoor roti", "Butter roti", "Plain nan", "Butter nan", "Plain kulcha", "Masala kulcha", "Tandoori lachha paratha", "Kashmiri nan" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList6MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jList6);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 59, 111, -1));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField2.setText("0");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 245, 120, -1));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField3.setText("0");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 245, 113, -1));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField4.setText("0");
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 245, 116, -1));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField5.setText("0");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 245, 111, -1));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField6.setText("0");
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 245, 111, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("South");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 20, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("North");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 20, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("Chinese");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 20, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("Veg");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("Rice");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 20, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setText("Tandoor");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 930, 280));

        jLabel9.setFont(new java.awt.Font("Colonna MT", 3, 72)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 51));
        jLabel9.setText("Menu");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 353, -1));

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 0));
        jButton1.setText("Total Amount");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 439, 122, -1));

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 423, 530, 58));

        jButton2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("Order");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 499, 582, 42));

        jButton3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 0, 0));
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 623, 582, 41));

        jButton4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 0, 0));
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 570, 582, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\Background-Design-Desktop-Wallpaper-16241.jpg")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1290, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList7MouseClicked
        Object[]Selected=jList7.getSelectedValues();
        int l=Selected.length;
        int total=0;
        for(int i=0; i<l; i++) {
            String Value=(String)Selected[i];
            if(Value.equals("Tea"))
                total=total+40;
            else   if(Value.equals("Coffee"))
                total=total+50;
            else if(Value.equals("Soft Drinks"))
                total=total+60;
            else if(Value.equals("Cold Coffee"))
                total=total+90;
            else if(Value.equals("Cold Coffee with Ice-Cream"))
                total=total+120;

        } jTextField8.setText(total+"");        // TODO add your handling code here:
}//GEN-LAST:event_jList7MouseClicked

    private void jList8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList8MouseClicked
        Object[]Selected=jList8.getSelectedValues();
        int l=Selected.length;
        int total=0;
        for(int i=0; i<l; i++) {
            String Value=(String)Selected[i];
            if(Value.equals("Green Salad"))
                total=total+40;
            else   if(Value.equals("Cucumber Salad"))
                total=total+50;
            else if(Value.equals("Fruit Salad"))
                total=total+110;
            else if(Value.equals("Dry Papad"))
                total=total+45;
            else if(Value.equals("Fry Papad"))
                total=total+55;

        } jTextField9.setText(total+"");   // TODO add your handling code here:
}//GEN-LAST:event_jList8MouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        Object[]Selected=jList1.getSelectedValues();
        int l=Selected.length;
        int total=0;
        for(int i=0; i<l; i++) {
            String Value=(String)Selected[i];
            if(Value.equals("Paneer masala dosa"))
                total=total+150;
            else   if(Value.equals("Onion sada dosa"))
                total=total+140;
            else if(Value.equals("Masala dosa"))
                total=total+130;
            else if(Value.equals("Paper roast dosa"))
                total=total+190;
            else if(Value.equals("Butter sada dosa"))
                total=total+150;
            else if(Value.equals("Onion vada"))
                total=total+145;
            else if(Value.equals("Sada vada"))
                total=total+165;
            else if(Value.equals("Veg upma"))
                total=total+185;
            else if(Value.equals("Sada upma"))
                total=total+130;
            else if(Value.equals("Halwa(Sweet)"))
                total=total+180;
            else if(Value.equals("Alu chop"))
                total=total+140;
            else if(Value.equals("Idli"))
                total=total+165;
            else if(Value.equals("Sambhar idli"))
                total=total+185;
        }
        jTextField1.setText(total+"");      // TODO add your handling code here:
}//GEN-LAST:event_jList1MouseClicked

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        Object[]Selected=jList2.getSelectedValues();
        int l=Selected.length;
        int total=0;
        for(int i=0; i<l; i++) {
            String Value=(String)Selected[i];
            if(Value.equals("Dal fry"))
                total=total+120;
            else   if(Value.equals("Dal tadka"))
                total=total+130;
            else if(Value.equals("Dal makini"))
                total=total+130;
            else if(Value.equals("Mix vegetable curry"))
                total=total+190;
            else if(Value.equals("Vegetable kurma"))
                total=total+150;
            else if(Value.equals("Aloo dum"))
                total=total+145;
            else if(Value.equals("Malai kofta"))
                total=total+165;
            else if(Value.equals("Paneer tikka masala"))
                total=total+185;
            else if(Value.equals("Kadai paneer"))
                total=total+145;
            else if(Value.equals("Paneer butter masala"))
                total=total+180;
            else if(Value.equals("Paneer bharta"))
                total=total+140;
            else if(Value.equals("Aloo kobi"))
                total=total+165;
            else if(Value.equals("Kobi masala"))
                total=total+185;
        }
        jTextField2.setText(total+"");       // TODO add your handling code here:
}//GEN-LAST:event_jList2MouseClicked

    private void jList3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList3MouseClicked
        Object[]Selected=jList3.getSelectedValues();
        int l=Selected.length;
        int total=0;
        for(int i=0; i<l; i++) {
            String Value=(String)Selected[i];
            if(Value.equals("Veg sweet corn soup"))
                total=total+178;
            else   if(Value.equals("Hot/soup"))
                total=total+140;
            else if(Value.equals("Lemon noodles soup"))
                total=total+130;
            else if(Value.equals("Manchurian soup"))
                total=total+190;
            else if(Value.equals("Tomato soup"))
                total=total+185;
            else if(Value.equals("Mushroom soup"))
                total=total+200;
            else if(Value.equals("Manchurian"))
                total=total+150;
            else if(Value.equals("Noodles"))
                total=total+145;
            else if(Value.equals("Veg haka noodles"))
                total=total+165;
        }
        jTextField3.setText(total+"");      // TODO add your handling code here:
}//GEN-LAST:event_jList3MouseClicked

    private void jList4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList4MouseClicked
        Object[]Selected=jList4.getSelectedValues();
        int l=Selected.length;
        int total=0;
        for(int i=0; i<l; i++) {
            String Value=(String)Selected[i];
            if(Value.equals("Veg-American chopsuey"))
                total=total+220;
            else   if(Value.equals("Mushroom chilly"))
                total=total+186;
            else if(Value.equals("Baby corn chilly"))
                total=total+178;
            else if(Value.equals("Potato chilly"))
                total=total+190;
            else if(Value.equals("Gobi chilly"))
                total=total+185;
            else if(Value.equals("Chana masala"))
                total=total+177;
            else if(Value.equals("Mattar paneer"))
                total=total+210;
            else if(Value.equals("Mushroom curry"))
                total=total+230;
            else if(Value.equals("Palak cream"))
                total=total+250;
        }
        jTextField4.setText(total+"");   // TODO add your handling code here:
}//GEN-LAST:event_jList4MouseClicked

    private void jList5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList5MouseClicked
        Object[]Selected=jList5.getSelectedValues();
        int l=Selected.length;
        int total=0;
        for(int i=0; i<l; i++) {
            String Value=(String)Selected[i];
            if(Value.equals("Plain rice"))
                total=total+150;
            else   if(Value.equals("Veg pulao"))
                total=total+140;
            else if(Value.equals("Green peas pulao"))
                total=total+130;
            else if(Value.equals("Sajan pulao"))
                total=total+190;
            else if(Value.equals("Kashmiri pulao"))
                total=total+195;
            else if(Value.equals("Veg fried rice"))
                total=total+185;
            else if(Value.equals("Veg-biryani"))
                total=total+150;
            else if(Value.equals("Jira-rice"))
                total=total+148;
            else if(Value.equals("Lemon rice"))
                total=total+145;
        } jTextField5.setText(total+"");      // TODO add your handling code here:
}//GEN-LAST:event_jList5MouseClicked

    private void jList6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList6MouseClicked
        Object[]Selected=jList6.getSelectedValues();
        int l=Selected.length;
        int total=0;
        for(int i=0; i<l; i++) {
            String Value=(String)Selected[i];
            if(Value.equals("Tawa roti"))
                total=total+85;
            else   if(Value.equals("Tandoor roti"))
                total=total+140;
            else if(Value.equals("Butter roti"))
                total=total+120;
            else if(Value.equals("Plain nan"))
                total=total+185;
            else if(Value.equals("Butter nan"))
                total=total+195;
            else if(Value.equals("Plain kulcha"))
                total=total+185;
            else if(Value.equals("Masala kulcha"))
                total=total+200;
            else if(Value.equals("Tandoori lachha paratha"))
                total=total+210;
            else if(Value.equals("Kashmiri nan"))
                total=total+160;
        } jTextField6.setText(total+"");     // TODO add your handling code here:
}//GEN-LAST:event_jList6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
            int t1=Integer.parseInt(jTextField1.getText());
            int t2=Integer.parseInt(jTextField2.getText());
            int t3=Integer.parseInt(jTextField3.getText());
            int t4=Integer.parseInt(jTextField4.getText());
            int t5=Integer.parseInt(jTextField5.getText());
            int t6=Integer.parseInt(jTextField6.getText());
            int t7=Integer.parseInt(jTextField8.getText());
            int t8=Integer.parseInt(jTextField9.getText());
            int t=t1+t2+t3+t4+t5+t6+t7+t8;

            jTextField7.setText(t+"");
            if(t==0)
            {
            jButton2.setEnabled(false);}  
            else
                
            { jButton2.setEnabled(true);}
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Please select all the fields"); }
        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(jTextField7==null)
               {
        this.setVisible(false);}
       else
        new NewJFrame18().setVisible(true);     // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        new NewJFrame19().setVisible(true);     // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
jTextField1.setText("0"); 
jTextField2.setText("0");
jTextField3.setText("0");
jTextField4.setText("0");jTextField6.setText("0");
jTextField5.setText("0");
jTextField7.setText(" ");
jTextField8.setText("0");
jTextField9.setText("0");
jButton2.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame17().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JList jList5;
    private javax.swing.JList jList6;
    private javax.swing.JList jList7;
    private javax.swing.JList jList8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
